# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mdal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mdal.proto',
  package='mdalgrpc',
  syntax='proto3',
  serialized_pb=_b('\n\nmdal.proto\x12\x08mdalgrpc\"\xdc\x02\n\x10\x44\x61taQueryRequest\x12\x13\n\x0b\x63omposition\x18\x01 \x03(\t\x12@\n\x0b\x61ggregation\x18\x02 \x03(\x0b\x32+.mdalgrpc.DataQueryRequest.AggregationEntry\x12<\n\tvariables\x18\x03 \x03(\x0b\x32).mdalgrpc.DataQueryRequest.VariablesEntry\x12\"\n\x04time\x18\x04 \x01(\x0b\x32\x14.mdalgrpc.TimeParams\x1aI\n\x10\x41ggregationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.mdalgrpc.Aggregation:\x02\x38\x01\x1a\x44\n\x0eVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.mdalgrpc.Variable:\x02\x38\x01\"J\n\x08Variable\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\x12\r\n\x05uuids\x18\x03 \x03(\x0c\x12\r\n\x05units\x18\x04 \x01(\t\"I\n\nTimeParams\x12\r\n\x05start\x18\x01 \x01(\t\x12\x0b\n\x03\x65nd\x18\x02 \x01(\t\x12\x0e\n\x06window\x18\x03 \x01(\t\x12\x0f\n\x07\x61ligned\x18\x04 \x01(\x08\"/\n\x0b\x41ggregation\x12 \n\x05\x66uncs\x18\x01 \x03(\x0e\x32\x11.mdalgrpc.AggFunc\"T\n\x11\x44\x61taQueryResponse\x12!\n\x07triples\x18\x01 \x03(\x0b\x32\x10.mdalgrpc.Triple\x12\r\n\x05uuids\x18\x02 \x03(\x0c\x12\r\n\x05\x61rrow\x18\x03 \x01(\x0c\":\n\x06Triple\x12\x0f\n\x07subject\x18\x01 \x01(\t\x12\x10\n\x08property\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t*B\n\x07\x41ggFunc\x12\x07\n\x03RAW\x10\x00\x12\x08\n\x04MEAN\x10\x01\x12\x07\n\x03MIN\x10\x02\x12\x07\n\x03MAX\x10\x03\x12\t\n\x05\x43OUNT\x10\x04\x12\x07\n\x03SUM\x10\x05\x32N\n\x04MDAL\x12\x46\n\tDataQuery\x12\x1a.mdalgrpc.DataQueryRequest\x1a\x1b.mdalgrpc.DataQueryResponse0\x01\x62\x06proto3')
)

_AGGFUNC = _descriptor.EnumDescriptor(
  name='AggFunc',
  full_name='mdalgrpc.AggFunc',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RAW', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEAN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MIN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COUNT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUM', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=721,
  serialized_end=787,
)
_sym_db.RegisterEnumDescriptor(_AGGFUNC)

AggFunc = enum_type_wrapper.EnumTypeWrapper(_AGGFUNC)
RAW = 0
MEAN = 1
MIN = 2
MAX = 3
COUNT = 4
SUM = 5



_DATAQUERYREQUEST_AGGREGATIONENTRY = _descriptor.Descriptor(
  name='AggregationEntry',
  full_name='mdalgrpc.DataQueryRequest.AggregationEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mdalgrpc.DataQueryRequest.AggregationEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mdalgrpc.DataQueryRequest.AggregationEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=303,
)

_DATAQUERYREQUEST_VARIABLESENTRY = _descriptor.Descriptor(
  name='VariablesEntry',
  full_name='mdalgrpc.DataQueryRequest.VariablesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mdalgrpc.DataQueryRequest.VariablesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mdalgrpc.DataQueryRequest.VariablesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=373,
)

_DATAQUERYREQUEST = _descriptor.Descriptor(
  name='DataQueryRequest',
  full_name='mdalgrpc.DataQueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='composition', full_name='mdalgrpc.DataQueryRequest.composition', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aggregation', full_name='mdalgrpc.DataQueryRequest.aggregation', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variables', full_name='mdalgrpc.DataQueryRequest.variables', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='mdalgrpc.DataQueryRequest.time', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATAQUERYREQUEST_AGGREGATIONENTRY, _DATAQUERYREQUEST_VARIABLESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=373,
)


_VARIABLE = _descriptor.Descriptor(
  name='Variable',
  full_name='mdalgrpc.Variable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mdalgrpc.Variable.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='definition', full_name='mdalgrpc.Variable.definition', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuids', full_name='mdalgrpc.Variable.uuids', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='units', full_name='mdalgrpc.Variable.units', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=449,
)


_TIMEPARAMS = _descriptor.Descriptor(
  name='TimeParams',
  full_name='mdalgrpc.TimeParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='mdalgrpc.TimeParams.start', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='mdalgrpc.TimeParams.end', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='window', full_name='mdalgrpc.TimeParams.window', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aligned', full_name='mdalgrpc.TimeParams.aligned', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=524,
)


_AGGREGATION = _descriptor.Descriptor(
  name='Aggregation',
  full_name='mdalgrpc.Aggregation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='funcs', full_name='mdalgrpc.Aggregation.funcs', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=573,
)


_DATAQUERYRESPONSE = _descriptor.Descriptor(
  name='DataQueryResponse',
  full_name='mdalgrpc.DataQueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='triples', full_name='mdalgrpc.DataQueryResponse.triples', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuids', full_name='mdalgrpc.DataQueryResponse.uuids', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrow', full_name='mdalgrpc.DataQueryResponse.arrow', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=659,
)


_TRIPLE = _descriptor.Descriptor(
  name='Triple',
  full_name='mdalgrpc.Triple',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subject', full_name='mdalgrpc.Triple.subject', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='property', full_name='mdalgrpc.Triple.property', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='mdalgrpc.Triple.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=719,
)

_DATAQUERYREQUEST_AGGREGATIONENTRY.fields_by_name['value'].message_type = _AGGREGATION
_DATAQUERYREQUEST_AGGREGATIONENTRY.containing_type = _DATAQUERYREQUEST
_DATAQUERYREQUEST_VARIABLESENTRY.fields_by_name['value'].message_type = _VARIABLE
_DATAQUERYREQUEST_VARIABLESENTRY.containing_type = _DATAQUERYREQUEST
_DATAQUERYREQUEST.fields_by_name['aggregation'].message_type = _DATAQUERYREQUEST_AGGREGATIONENTRY
_DATAQUERYREQUEST.fields_by_name['variables'].message_type = _DATAQUERYREQUEST_VARIABLESENTRY
_DATAQUERYREQUEST.fields_by_name['time'].message_type = _TIMEPARAMS
_AGGREGATION.fields_by_name['funcs'].enum_type = _AGGFUNC
_DATAQUERYRESPONSE.fields_by_name['triples'].message_type = _TRIPLE
DESCRIPTOR.message_types_by_name['DataQueryRequest'] = _DATAQUERYREQUEST
DESCRIPTOR.message_types_by_name['Variable'] = _VARIABLE
DESCRIPTOR.message_types_by_name['TimeParams'] = _TIMEPARAMS
DESCRIPTOR.message_types_by_name['Aggregation'] = _AGGREGATION
DESCRIPTOR.message_types_by_name['DataQueryResponse'] = _DATAQUERYRESPONSE
DESCRIPTOR.message_types_by_name['Triple'] = _TRIPLE
DESCRIPTOR.enum_types_by_name['AggFunc'] = _AGGFUNC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataQueryRequest = _reflection.GeneratedProtocolMessageType('DataQueryRequest', (_message.Message,), dict(

  AggregationEntry = _reflection.GeneratedProtocolMessageType('AggregationEntry', (_message.Message,), dict(
    DESCRIPTOR = _DATAQUERYREQUEST_AGGREGATIONENTRY,
    __module__ = 'mdal_pb2'
    # @@protoc_insertion_point(class_scope:mdalgrpc.DataQueryRequest.AggregationEntry)
    ))
  ,

  VariablesEntry = _reflection.GeneratedProtocolMessageType('VariablesEntry', (_message.Message,), dict(
    DESCRIPTOR = _DATAQUERYREQUEST_VARIABLESENTRY,
    __module__ = 'mdal_pb2'
    # @@protoc_insertion_point(class_scope:mdalgrpc.DataQueryRequest.VariablesEntry)
    ))
  ,
  DESCRIPTOR = _DATAQUERYREQUEST,
  __module__ = 'mdal_pb2'
  # @@protoc_insertion_point(class_scope:mdalgrpc.DataQueryRequest)
  ))
_sym_db.RegisterMessage(DataQueryRequest)
_sym_db.RegisterMessage(DataQueryRequest.AggregationEntry)
_sym_db.RegisterMessage(DataQueryRequest.VariablesEntry)

Variable = _reflection.GeneratedProtocolMessageType('Variable', (_message.Message,), dict(
  DESCRIPTOR = _VARIABLE,
  __module__ = 'mdal_pb2'
  # @@protoc_insertion_point(class_scope:mdalgrpc.Variable)
  ))
_sym_db.RegisterMessage(Variable)

TimeParams = _reflection.GeneratedProtocolMessageType('TimeParams', (_message.Message,), dict(
  DESCRIPTOR = _TIMEPARAMS,
  __module__ = 'mdal_pb2'
  # @@protoc_insertion_point(class_scope:mdalgrpc.TimeParams)
  ))
_sym_db.RegisterMessage(TimeParams)

Aggregation = _reflection.GeneratedProtocolMessageType('Aggregation', (_message.Message,), dict(
  DESCRIPTOR = _AGGREGATION,
  __module__ = 'mdal_pb2'
  # @@protoc_insertion_point(class_scope:mdalgrpc.Aggregation)
  ))
_sym_db.RegisterMessage(Aggregation)

DataQueryResponse = _reflection.GeneratedProtocolMessageType('DataQueryResponse', (_message.Message,), dict(
  DESCRIPTOR = _DATAQUERYRESPONSE,
  __module__ = 'mdal_pb2'
  # @@protoc_insertion_point(class_scope:mdalgrpc.DataQueryResponse)
  ))
_sym_db.RegisterMessage(DataQueryResponse)

Triple = _reflection.GeneratedProtocolMessageType('Triple', (_message.Message,), dict(
  DESCRIPTOR = _TRIPLE,
  __module__ = 'mdal_pb2'
  # @@protoc_insertion_point(class_scope:mdalgrpc.Triple)
  ))
_sym_db.RegisterMessage(Triple)


_DATAQUERYREQUEST_AGGREGATIONENTRY.has_options = True
_DATAQUERYREQUEST_AGGREGATIONENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_DATAQUERYREQUEST_VARIABLESENTRY.has_options = True
_DATAQUERYREQUEST_VARIABLESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_MDAL = _descriptor.ServiceDescriptor(
  name='MDAL',
  full_name='mdalgrpc.MDAL',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=789,
  serialized_end=867,
  methods=[
  _descriptor.MethodDescriptor(
    name='DataQuery',
    full_name='mdalgrpc.MDAL.DataQuery',
    index=0,
    containing_service=None,
    input_type=_DATAQUERYREQUEST,
    output_type=_DATAQUERYRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MDAL)

DESCRIPTOR.services_by_name['MDAL'] = _MDAL

# @@protoc_insertion_point(module_scope)
