// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mdal.proto

package mdalgrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AggFunc int32

const (
	AggFunc_RAW   AggFunc = 0
	AggFunc_MEAN  AggFunc = 1
	AggFunc_MIN   AggFunc = 2
	AggFunc_MAX   AggFunc = 3
	AggFunc_COUNT AggFunc = 4
	AggFunc_SUM   AggFunc = 5
)

var AggFunc_name = map[int32]string{
	0: "RAW",
	1: "MEAN",
	2: "MIN",
	3: "MAX",
	4: "COUNT",
	5: "SUM",
}

var AggFunc_value = map[string]int32{
	"RAW":   0,
	"MEAN":  1,
	"MIN":   2,
	"MAX":   3,
	"COUNT": 4,
	"SUM":   5,
}

func (x AggFunc) String() string {
	return proto.EnumName(AggFunc_name, int32(x))
}

func (AggFunc) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_20e1752e2497525f, []int{0}
}

type DataQueryRequest struct {
	Composition          []string                `protobuf:"bytes,1,rep,name=composition,proto3" json:"composition,omitempty"`
	Aggregation          map[string]*Aggregation `protobuf:"bytes,2,rep,name=aggregation,proto3" json:"aggregation,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Variables            map[string]*Variable    `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Time                 *TimeParams             `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DataQueryRequest) Reset()         { *m = DataQueryRequest{} }
func (m *DataQueryRequest) String() string { return proto.CompactTextString(m) }
func (*DataQueryRequest) ProtoMessage()    {}
func (*DataQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_20e1752e2497525f, []int{0}
}

func (m *DataQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataQueryRequest.Unmarshal(m, b)
}
func (m *DataQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataQueryRequest.Marshal(b, m, deterministic)
}
func (m *DataQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataQueryRequest.Merge(m, src)
}
func (m *DataQueryRequest) XXX_Size() int {
	return xxx_messageInfo_DataQueryRequest.Size(m)
}
func (m *DataQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataQueryRequest proto.InternalMessageInfo

func (m *DataQueryRequest) GetComposition() []string {
	if m != nil {
		return m.Composition
	}
	return nil
}

func (m *DataQueryRequest) GetAggregation() map[string]*Aggregation {
	if m != nil {
		return m.Aggregation
	}
	return nil
}

func (m *DataQueryRequest) GetVariables() map[string]*Variable {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *DataQueryRequest) GetTime() *TimeParams {
	if m != nil {
		return m.Time
	}
	return nil
}

type Variable struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Definition           string   `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	Uuids                []string `protobuf:"bytes,3,rep,name=uuids,proto3" json:"uuids,omitempty"`
	Units                string   `protobuf:"bytes,4,opt,name=units,proto3" json:"units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Variable) Reset()         { *m = Variable{} }
func (m *Variable) String() string { return proto.CompactTextString(m) }
func (*Variable) ProtoMessage()    {}
func (*Variable) Descriptor() ([]byte, []int) {
	return fileDescriptor_20e1752e2497525f, []int{1}
}

func (m *Variable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variable.Unmarshal(m, b)
}
func (m *Variable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variable.Marshal(b, m, deterministic)
}
func (m *Variable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variable.Merge(m, src)
}
func (m *Variable) XXX_Size() int {
	return xxx_messageInfo_Variable.Size(m)
}
func (m *Variable) XXX_DiscardUnknown() {
	xxx_messageInfo_Variable.DiscardUnknown(m)
}

var xxx_messageInfo_Variable proto.InternalMessageInfo

func (m *Variable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Variable) GetDefinition() string {
	if m != nil {
		return m.Definition
	}
	return ""
}

func (m *Variable) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *Variable) GetUnits() string {
	if m != nil {
		return m.Units
	}
	return ""
}

type TimeParams struct {
	Start                string   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  string   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Window               string   `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	Aligned              bool     `protobuf:"varint,4,opt,name=aligned,proto3" json:"aligned,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeParams) Reset()         { *m = TimeParams{} }
func (m *TimeParams) String() string { return proto.CompactTextString(m) }
func (*TimeParams) ProtoMessage()    {}
func (*TimeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_20e1752e2497525f, []int{2}
}

func (m *TimeParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeParams.Unmarshal(m, b)
}
func (m *TimeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeParams.Marshal(b, m, deterministic)
}
func (m *TimeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeParams.Merge(m, src)
}
func (m *TimeParams) XXX_Size() int {
	return xxx_messageInfo_TimeParams.Size(m)
}
func (m *TimeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeParams.DiscardUnknown(m)
}

var xxx_messageInfo_TimeParams proto.InternalMessageInfo

func (m *TimeParams) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *TimeParams) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func (m *TimeParams) GetWindow() string {
	if m != nil {
		return m.Window
	}
	return ""
}

func (m *TimeParams) GetAligned() bool {
	if m != nil {
		return m.Aligned
	}
	return false
}

type Aggregation struct {
	Funcs                []AggFunc `protobuf:"varint,1,rep,packed,name=funcs,proto3,enum=mdalgrpc.AggFunc" json:"funcs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Aggregation) Reset()         { *m = Aggregation{} }
func (m *Aggregation) String() string { return proto.CompactTextString(m) }
func (*Aggregation) ProtoMessage()    {}
func (*Aggregation) Descriptor() ([]byte, []int) {
	return fileDescriptor_20e1752e2497525f, []int{3}
}

func (m *Aggregation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Aggregation.Unmarshal(m, b)
}
func (m *Aggregation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Aggregation.Marshal(b, m, deterministic)
}
func (m *Aggregation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Aggregation.Merge(m, src)
}
func (m *Aggregation) XXX_Size() int {
	return xxx_messageInfo_Aggregation.Size(m)
}
func (m *Aggregation) XXX_DiscardUnknown() {
	xxx_messageInfo_Aggregation.DiscardUnknown(m)
}

var xxx_messageInfo_Aggregation proto.InternalMessageInfo

func (m *Aggregation) GetFuncs() []AggFunc {
	if m != nil {
		return m.Funcs
	}
	return nil
}

type DataQueryResponse struct {
	// TODO: need to transform this from list of triples to a map
	// keyed by UUID of the triples relevant to that UUID
	Rows []*DataQueryResponse_Row `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	// variable name -> list of uuids
	Mapping map[string]*DataQueryResponse_VarMap `protobuf:"bytes,2,rep,name=mapping,proto3" json:"mapping,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// uuid -> triple context
	Context []*DataQueryResponse_Row `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty"`
	Uuids   []string                 `protobuf:"bytes,4,rep,name=uuids,proto3" json:"uuids,omitempty"`
	// apache arrow serialized response
	Arrow                []byte                          `protobuf:"bytes,5,opt,name=arrow,proto3" json:"arrow,omitempty"`
	Error                string                          `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Times                []int64                         `protobuf:"varint,7,rep,packed,name=times,proto3" json:"times,omitempty"`
	Values               []*DataQueryResponse_ValueArray `protobuf:"bytes,8,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *DataQueryResponse) Reset()         { *m = DataQueryResponse{} }
func (m *DataQueryResponse) String() string { return proto.CompactTextString(m) }
func (*DataQueryResponse) ProtoMessage()    {}
func (*DataQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20e1752e2497525f, []int{4}
}

func (m *DataQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataQueryResponse.Unmarshal(m, b)
}
func (m *DataQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataQueryResponse.Marshal(b, m, deterministic)
}
func (m *DataQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataQueryResponse.Merge(m, src)
}
func (m *DataQueryResponse) XXX_Size() int {
	return xxx_messageInfo_DataQueryResponse.Size(m)
}
func (m *DataQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataQueryResponse proto.InternalMessageInfo

func (m *DataQueryResponse) GetRows() []*DataQueryResponse_Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *DataQueryResponse) GetMapping() map[string]*DataQueryResponse_VarMap {
	if m != nil {
		return m.Mapping
	}
	return nil
}

func (m *DataQueryResponse) GetContext() []*DataQueryResponse_Row {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *DataQueryResponse) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *DataQueryResponse) GetArrow() []byte {
	if m != nil {
		return m.Arrow
	}
	return nil
}

func (m *DataQueryResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DataQueryResponse) GetTimes() []int64 {
	if m != nil {
		return m.Times
	}
	return nil
}

func (m *DataQueryResponse) GetValues() []*DataQueryResponse_ValueArray {
	if m != nil {
		return m.Values
	}
	return nil
}

type DataQueryResponse_Row struct {
	Uuid                 string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Row                  map[string]string `protobuf:"bytes,2,rep,name=row,proto3" json:"row,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DataQueryResponse_Row) Reset()         { *m = DataQueryResponse_Row{} }
func (m *DataQueryResponse_Row) String() string { return proto.CompactTextString(m) }
func (*DataQueryResponse_Row) ProtoMessage()    {}
func (*DataQueryResponse_Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_20e1752e2497525f, []int{4, 0}
}

func (m *DataQueryResponse_Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataQueryResponse_Row.Unmarshal(m, b)
}
func (m *DataQueryResponse_Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataQueryResponse_Row.Marshal(b, m, deterministic)
}
func (m *DataQueryResponse_Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataQueryResponse_Row.Merge(m, src)
}
func (m *DataQueryResponse_Row) XXX_Size() int {
	return xxx_messageInfo_DataQueryResponse_Row.Size(m)
}
func (m *DataQueryResponse_Row) XXX_DiscardUnknown() {
	xxx_messageInfo_DataQueryResponse_Row.DiscardUnknown(m)
}

var xxx_messageInfo_DataQueryResponse_Row proto.InternalMessageInfo

func (m *DataQueryResponse_Row) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DataQueryResponse_Row) GetRow() map[string]string {
	if m != nil {
		return m.Row
	}
	return nil
}

type DataQueryResponse_VarMap struct {
	Uuids                [][]byte `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataQueryResponse_VarMap) Reset()         { *m = DataQueryResponse_VarMap{} }
func (m *DataQueryResponse_VarMap) String() string { return proto.CompactTextString(m) }
func (*DataQueryResponse_VarMap) ProtoMessage()    {}
func (*DataQueryResponse_VarMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_20e1752e2497525f, []int{4, 1}
}

func (m *DataQueryResponse_VarMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataQueryResponse_VarMap.Unmarshal(m, b)
}
func (m *DataQueryResponse_VarMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataQueryResponse_VarMap.Marshal(b, m, deterministic)
}
func (m *DataQueryResponse_VarMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataQueryResponse_VarMap.Merge(m, src)
}
func (m *DataQueryResponse_VarMap) XXX_Size() int {
	return xxx_messageInfo_DataQueryResponse_VarMap.Size(m)
}
func (m *DataQueryResponse_VarMap) XXX_DiscardUnknown() {
	xxx_messageInfo_DataQueryResponse_VarMap.DiscardUnknown(m)
}

var xxx_messageInfo_DataQueryResponse_VarMap proto.InternalMessageInfo

func (m *DataQueryResponse_VarMap) GetUuids() [][]byte {
	if m != nil {
		return m.Uuids
	}
	return nil
}

type DataQueryResponse_ValueArray struct {
	Value                []float64 `protobuf:"fixed64,1,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DataQueryResponse_ValueArray) Reset()         { *m = DataQueryResponse_ValueArray{} }
func (m *DataQueryResponse_ValueArray) String() string { return proto.CompactTextString(m) }
func (*DataQueryResponse_ValueArray) ProtoMessage()    {}
func (*DataQueryResponse_ValueArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_20e1752e2497525f, []int{4, 2}
}

func (m *DataQueryResponse_ValueArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataQueryResponse_ValueArray.Unmarshal(m, b)
}
func (m *DataQueryResponse_ValueArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataQueryResponse_ValueArray.Marshal(b, m, deterministic)
}
func (m *DataQueryResponse_ValueArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataQueryResponse_ValueArray.Merge(m, src)
}
func (m *DataQueryResponse_ValueArray) XXX_Size() int {
	return xxx_messageInfo_DataQueryResponse_ValueArray.Size(m)
}
func (m *DataQueryResponse_ValueArray) XXX_DiscardUnknown() {
	xxx_messageInfo_DataQueryResponse_ValueArray.DiscardUnknown(m)
}

var xxx_messageInfo_DataQueryResponse_ValueArray proto.InternalMessageInfo

func (m *DataQueryResponse_ValueArray) GetValue() []float64 {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterEnum("mdalgrpc.AggFunc", AggFunc_name, AggFunc_value)
	proto.RegisterType((*DataQueryRequest)(nil), "mdalgrpc.DataQueryRequest")
	proto.RegisterMapType((map[string]*Aggregation)(nil), "mdalgrpc.DataQueryRequest.AggregationEntry")
	proto.RegisterMapType((map[string]*Variable)(nil), "mdalgrpc.DataQueryRequest.VariablesEntry")
	proto.RegisterType((*Variable)(nil), "mdalgrpc.Variable")
	proto.RegisterType((*TimeParams)(nil), "mdalgrpc.TimeParams")
	proto.RegisterType((*Aggregation)(nil), "mdalgrpc.Aggregation")
	proto.RegisterType((*DataQueryResponse)(nil), "mdalgrpc.DataQueryResponse")
	proto.RegisterMapType((map[string]*DataQueryResponse_VarMap)(nil), "mdalgrpc.DataQueryResponse.MappingEntry")
	proto.RegisterType((*DataQueryResponse_Row)(nil), "mdalgrpc.DataQueryResponse.Row")
	proto.RegisterMapType((map[string]string)(nil), "mdalgrpc.DataQueryResponse.Row.RowEntry")
	proto.RegisterType((*DataQueryResponse_VarMap)(nil), "mdalgrpc.DataQueryResponse.VarMap")
	proto.RegisterType((*DataQueryResponse_ValueArray)(nil), "mdalgrpc.DataQueryResponse.ValueArray")
}

func init() { proto.RegisterFile("mdal.proto", fileDescriptor_20e1752e2497525f) }

var fileDescriptor_20e1752e2497525f = []byte{
	// 743 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xbe, 0x8e, 0x9d, 0xbf, 0x93, 0xaa, 0xd7, 0x9d, 0x9b, 0x7b, 0xe5, 0x6b, 0x50, 0x89, 0xbc,
	0x00, 0xd3, 0x4a, 0x09, 0xa4, 0x52, 0x55, 0xba, 0x40, 0x4a, 0x69, 0x41, 0x48, 0xa4, 0x94, 0xa1,
	0x2d, 0xac, 0x90, 0xa6, 0xc9, 0xd4, 0x32, 0x24, 0x33, 0xee, 0xd8, 0x69, 0xc8, 0x96, 0x3d, 0xab,
	0x3e, 0x00, 0x6f, 0xc4, 0x86, 0x57, 0xe0, 0x41, 0xd0, 0xcc, 0xd8, 0xb5, 0x53, 0x85, 0x80, 0x58,
	0x54, 0x9a, 0x73, 0xe6, 0x3b, 0xdf, 0x77, 0x7c, 0xce, 0x37, 0x0d, 0xc0, 0x78, 0x48, 0x46, 0xed,
	0x48, 0xf0, 0x84, 0xa3, 0x9a, 0x3c, 0x07, 0x22, 0x1a, 0xb8, 0xb7, 0x03, 0xce, 0x83, 0x11, 0xed,
	0x90, 0x28, 0xec, 0x10, 0xc6, 0x78, 0x42, 0x92, 0x90, 0xb3, 0x58, 0xe3, 0xbc, 0x2f, 0x26, 0xd8,
	0xfb, 0x24, 0x21, 0xaf, 0x26, 0x54, 0xcc, 0x30, 0xbd, 0x98, 0xd0, 0x38, 0x41, 0x2d, 0x68, 0x0c,
	0xf8, 0x38, 0xe2, 0x71, 0x28, 0xa1, 0x8e, 0xd1, 0x32, 0xfd, 0x3a, 0x2e, 0xa6, 0x50, 0x1f, 0x1a,
	0x24, 0x08, 0x04, 0x0d, 0x14, 0x99, 0x53, 0x6a, 0x99, 0x7e, 0xa3, 0xbb, 0xd9, 0xce, 0x44, 0xdb,
	0x37, 0x29, 0xdb, 0xbd, 0x1c, 0x7d, 0xc0, 0x12, 0x31, 0xc3, 0xc5, 0x7a, 0xf4, 0x0c, 0xea, 0x97,
	0x44, 0x84, 0xe4, 0x6c, 0x44, 0x63, 0xc7, 0x54, 0x64, 0xf7, 0x97, 0x90, 0x9d, 0x66, 0x58, 0x4d,
	0x95, 0xd7, 0x22, 0x1f, 0xac, 0x24, 0x1c, 0x53, 0xc7, 0x6a, 0x19, 0x7e, 0xa3, 0xdb, 0xcc, 0x39,
	0x8e, 0xc3, 0x31, 0x3d, 0x22, 0x82, 0x8c, 0x63, 0xac, 0x10, 0xee, 0x09, 0xd8, 0x37, 0x7b, 0x42,
	0x36, 0x98, 0x1f, 0xe8, 0xcc, 0x31, 0x5a, 0x86, 0x5f, 0xc7, 0xf2, 0x88, 0x36, 0xa1, 0x7c, 0x49,
	0x46, 0x13, 0xea, 0x94, 0x14, 0xe1, 0xbf, 0x39, 0x61, 0xa1, 0x18, 0x6b, 0xcc, 0x6e, 0x69, 0xc7,
	0x70, 0x8f, 0x60, 0x75, 0xbe, 0xbb, 0x05, 0xa4, 0xfe, 0x3c, 0x29, 0xca, 0x49, 0xb3, 0xd2, 0x02,
	0xa3, 0xf7, 0x1e, 0x6a, 0x59, 0x1a, 0x21, 0xb0, 0x18, 0x19, 0xd3, 0x94, 0x4c, 0x9d, 0xd1, 0x3a,
	0xc0, 0x90, 0x9e, 0x87, 0x2c, 0x4c, 0x37, 0x21, 0x6f, 0x0a, 0x19, 0xd4, 0x84, 0xf2, 0x64, 0x12,
	0x0e, 0xf5, 0x5c, 0xeb, 0x58, 0x07, 0x2a, 0xcb, 0xc2, 0x24, 0x56, 0x93, 0x92, 0x59, 0x19, 0x78,
	0xe7, 0x00, 0xf9, 0xa0, 0x24, 0x26, 0x4e, 0x88, 0x48, 0x52, 0x39, 0x1d, 0xc8, 0xef, 0xa1, 0x6c,
	0x98, 0x0a, 0xc9, 0x23, 0xfa, 0x0f, 0x2a, 0xd3, 0x90, 0x0d, 0xf9, 0xd4, 0x31, 0x55, 0x32, 0x8d,
	0x90, 0x03, 0x55, 0x32, 0x0a, 0x03, 0x46, 0x87, 0x4a, 0xa5, 0x86, 0xb3, 0xd0, 0xdb, 0x86, 0x46,
	0x61, 0x7e, 0xe8, 0x1e, 0x94, 0xcf, 0x27, 0x6c, 0x10, 0x2b, 0xa7, 0xad, 0x76, 0xd7, 0xe6, 0xa6,
	0xfc, 0x74, 0xc2, 0x06, 0x58, 0xdf, 0x7b, 0x57, 0x65, 0x58, 0x2b, 0xb8, 0x21, 0x8e, 0x38, 0x8b,
	0x29, 0xda, 0x02, 0x4b, 0xf0, 0xa9, 0xae, 0x6e, 0x74, 0xef, 0x2c, 0x34, 0x8e, 0x86, 0xb6, 0x31,
	0x9f, 0x62, 0x05, 0x46, 0x7b, 0x50, 0x1d, 0x93, 0x28, 0x0a, 0x59, 0x90, 0xba, 0xd7, 0x5f, 0x56,
	0xd7, 0xd7, 0x50, 0xed, 0xb7, 0xac, 0x10, 0x3d, 0x82, 0xea, 0x80, 0xb3, 0x84, 0x7e, 0x4c, 0x52,
	0xd3, 0xfe, 0x52, 0x3b, 0xc3, 0xe7, 0x5b, 0xb1, 0x6e, 0x6c, 0x85, 0x08, 0xc1, 0xa7, 0x4e, 0xb9,
	0x65, 0xf8, 0x2b, 0x58, 0x07, 0x32, 0x4b, 0x85, 0xe0, 0xc2, 0xa9, 0xe8, 0x3d, 0xa8, 0x40, 0x66,
	0xa5, 0x91, 0x63, 0xa7, 0xda, 0x32, 0x7d, 0x13, 0xeb, 0x00, 0x3d, 0x86, 0x8a, 0xb2, 0x4e, 0xec,
	0xd4, 0x54, 0x47, 0x77, 0x97, 0x75, 0x74, 0x2a, 0x91, 0x3d, 0x21, 0xc8, 0x0c, 0xa7, 0x55, 0xee,
	0x67, 0x03, 0x4c, 0xcc, 0xa7, 0xd2, 0x69, 0xb2, 0xa5, 0xcc, 0x69, 0xf2, 0x8c, 0x76, 0xc1, 0x94,
	0xbd, 0xfd, 0xc6, 0xb8, 0x30, 0x9f, 0xca, 0x3f, 0x3d, 0x2e, 0x59, 0xe4, 0x6e, 0x43, 0x2d, 0x4b,
	0x2c, 0x78, 0x11, 0xcd, 0xe2, 0x8b, 0xa8, 0x17, 0xdf, 0xd3, 0x3a, 0x54, 0x4e, 0x89, 0xe8, 0x93,
	0x28, 0x9f, 0x98, 0x5c, 0xf3, 0x4a, 0x3a, 0x31, 0xd7, 0x03, 0xc8, 0xbf, 0x22, 0xe7, 0x91, 0x18,
	0x23, 0xe5, 0x71, 0xdf, 0xc1, 0x4a, 0x71, 0x7f, 0x0b, 0xf4, 0x77, 0xe6, 0x5f, 0xa4, 0xb7, 0x7c,
	0x68, 0xb2, 0x9d, 0x42, 0x8f, 0x1b, 0x7b, 0x50, 0x4d, 0x7d, 0x8a, 0xaa, 0x60, 0xe2, 0xde, 0x1b,
	0xfb, 0x2f, 0x54, 0x03, 0xab, 0x7f, 0xd0, 0x3b, 0xb4, 0x0d, 0x99, 0xea, 0x3f, 0x3f, 0xb4, 0x4b,
	0xea, 0xd0, 0x7b, 0x6b, 0x9b, 0xa8, 0x0e, 0xe5, 0x27, 0x2f, 0x4f, 0x0e, 0x8f, 0x6d, 0x4b, 0xe6,
	0x5e, 0x9f, 0xf4, 0xed, 0x72, 0xf7, 0xab, 0x01, 0x56, 0x7f, 0xbf, 0xf7, 0x02, 0x11, 0xa8, 0x5f,
	0x6b, 0x22, 0xf7, 0xe7, 0xff, 0x04, 0xdd, 0x5b, 0x4b, 0x9a, 0xf4, 0xfe, 0xff, 0xf4, 0xed, 0xfb,
	0x55, 0xe9, 0x1f, 0x6f, 0xb5, 0x73, 0xf9, 0xb0, 0x23, 0x71, 0x9d, 0x0b, 0x79, 0xbf, 0x6b, 0x6c,
	0x3c, 0x30, 0xd0, 0x00, 0xe0, 0xba, 0xa2, 0xfb, 0xe7, 0x1a, 0xae, 0xd2, 0x68, 0x7a, 0x7f, 0xcf,
	0x6b, 0x74, 0x95, 0xc8, 0x59, 0x45, 0xfd, 0xbe, 0x6c, 0xfd, 0x08, 0x00, 0x00, 0xff, 0xff, 0x44,
	0xde, 0x65, 0x5a, 0x95, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MDALClient is the client API for MDAL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MDALClient interface {
	DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (MDAL_DataQueryClient, error)
	DataQuery2(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (MDAL_DataQuery2Client, error)
}

type mDALClient struct {
	cc *grpc.ClientConn
}

func NewMDALClient(cc *grpc.ClientConn) MDALClient {
	return &mDALClient{cc}
}

func (c *mDALClient) DataQuery(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (MDAL_DataQueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MDAL_serviceDesc.Streams[0], "/mdalgrpc.MDAL/DataQuery", opts...)
	if err != nil {
		return nil, err
	}
	x := &mDALDataQueryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MDAL_DataQueryClient interface {
	Recv() (*DataQueryResponse, error)
	grpc.ClientStream
}

type mDALDataQueryClient struct {
	grpc.ClientStream
}

func (x *mDALDataQueryClient) Recv() (*DataQueryResponse, error) {
	m := new(DataQueryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mDALClient) DataQuery2(ctx context.Context, in *DataQueryRequest, opts ...grpc.CallOption) (MDAL_DataQuery2Client, error) {
	stream, err := c.cc.NewStream(ctx, &_MDAL_serviceDesc.Streams[1], "/mdalgrpc.MDAL/DataQuery2", opts...)
	if err != nil {
		return nil, err
	}
	x := &mDALDataQuery2Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MDAL_DataQuery2Client interface {
	Recv() (*DataQueryResponse, error)
	grpc.ClientStream
}

type mDALDataQuery2Client struct {
	grpc.ClientStream
}

func (x *mDALDataQuery2Client) Recv() (*DataQueryResponse, error) {
	m := new(DataQueryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MDALServer is the server API for MDAL service.
type MDALServer interface {
	DataQuery(*DataQueryRequest, MDAL_DataQueryServer) error
	DataQuery2(*DataQueryRequest, MDAL_DataQuery2Server) error
}

func RegisterMDALServer(s *grpc.Server, srv MDALServer) {
	s.RegisterService(&_MDAL_serviceDesc, srv)
}

func _MDAL_DataQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DataQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MDALServer).DataQuery(m, &mDALDataQueryServer{stream})
}

type MDAL_DataQueryServer interface {
	Send(*DataQueryResponse) error
	grpc.ServerStream
}

type mDALDataQueryServer struct {
	grpc.ServerStream
}

func (x *mDALDataQueryServer) Send(m *DataQueryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MDAL_DataQuery2_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DataQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MDALServer).DataQuery2(m, &mDALDataQuery2Server{stream})
}

type MDAL_DataQuery2Server interface {
	Send(*DataQueryResponse) error
	grpc.ServerStream
}

type mDALDataQuery2Server struct {
	grpc.ServerStream
}

func (x *mDALDataQuery2Server) Send(m *DataQueryResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MDAL_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mdalgrpc.MDAL",
	HandlerType: (*MDALServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DataQuery",
			Handler:       _MDAL_DataQuery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DataQuery2",
			Handler:       _MDAL_DataQuery2_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mdal.proto",
}
